### ISSUE TITLE
Import profile

### ISSUE THREAD

**Issue by flyingzebras** [leibovic/copy-profile#2]
Copy Profile is used to export the profile, but how do I import it?

**Comment by pierreonthenet** [comment]
For now, it seems like you can't do it. Maybe in the next version ? I'll love to be able to do that !

**Comment by leibovic** [comment]
This is technically very hard to do, and I would not advise trying to do this with an add-on. This add-on is designed as a way to inspect a profile for debugging purposes, not act as a restore option.

**Comment by pierreonthenet** [comment]
Thank you for your response !
Too bad it is technically complicated... this means that I can't delete the useless "adblockplus" folder that takes me 20Mo in my phone memory... :'-(

Why do you advise to do not trying to restore a profile folder ?

**Comment by flyingzebras** [comment]
@leibovic "This add-on is designed as a way to inspect a profile for debugging purposes, not act as a restore option." Can you please add that to the description of this add-on?

**Comment by leibovic** [comment]
@pierreonthenet Your issue with ABP sounds like a separate issue. Did removing the add-on still leave that folder there?

What you could do is modify this add-on to delete that folder and install that locally. Otherwise, what you're asking for is a "reset Firefox" feature.

**Comment by leibovic** [comment]
@pierreonthenet I don't advise trying to restore the profile folder because things like the databases stored there are not designed to be replaced mid-flight.

**Comment by pierreonthenet** [comment]
@leibovic Thank you for your responses !
The ABP bug is a separate issue, I just talked about it as an exemple of why a restore option would be useful. And, no, removing ABP extension isn't working at all... :'-(
I don't know how to make Firefox Extension, so making a "Profile Explorer" extension, to be able to delete a folder in the Profile, seems very difficult to me.

**Comment by pierreonthenet** [comment]
Hi ! Thanks to your code, I was able to make my own first Firefox Extension, that I used to delete files that took too much place : https://github.com/pierreonthenet/delete-private-files-android-firefox-addon

Thank you again !
